# Generated by Django 4.2.3 on 2023-07-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Details',
            new_name='User_Detail',
        ),
    ]
